### ISSUE TITLE
Crash on 421 Source

### ISSUE THREAD

**Issue by BastiBlue** [alexhajdu/fix_this#6]
i have random crashes on 4.21.1 source.

Project Crashlog:  LogOutputDevice: Warning: Script Stack (0 frames):

![error](https://user-images.githubusercontent.com/12150688/50402799-9f914800-0799-11e9-977f-1edb7a6fdaef.png)

**Comment by alexhajdu** [comment]
@BastiBlue thanks for the report. I'll take a look!

**Comment by alexhajdu** [comment]
Fixed
